// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNPnggGhZ7tUeeGDRwVY61i9Zv3voh1k',
    appId: '1:487822294670:web:d2805f07ee849d980a53df',
    messagingSenderId: '487822294670',
    projectId: 'door-alert-system',
    authDomain: 'door-alert-system.firebaseapp.com',
    databaseURL: 'https://door-alert-system-default-rtdb.firebaseio.com',
    storageBucket: 'door-alert-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGQAT2FccvEclcGXuea5y6aDCMVZsCFvU',
    appId: '1:487822294670:android:4fbd30365f2692090a53df',
    messagingSenderId: '487822294670',
    projectId: 'door-alert-system',
    databaseURL: 'https://door-alert-system-default-rtdb.firebaseio.com',
    storageBucket: 'door-alert-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJjo5t7cAr0ZDRiDxnhf9vMk0A9sSRKg',
    appId: '1:487822294670:ios:569105db03483da70a53df',
    messagingSenderId: '487822294670',
    projectId: 'door-alert-system',
    databaseURL: 'https://door-alert-system-default-rtdb.firebaseio.com',
    storageBucket: 'door-alert-system.firebasestorage.app',
    iosBundleId: 'com.example.pirMotionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTJjo5t7cAr0ZDRiDxnhf9vMk0A9sSRKg',
    appId: '1:487822294670:ios:569105db03483da70a53df',
    messagingSenderId: '487822294670',
    projectId: 'door-alert-system',
    databaseURL: 'https://door-alert-system-default-rtdb.firebaseio.com',
    storageBucket: 'door-alert-system.firebasestorage.app',
    iosBundleId: 'com.example.pirMotionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNPnggGhZ7tUeeGDRwVY61i9Zv3voh1k',
    appId: '1:487822294670:web:6f37fd64bb5c46090a53df',
    messagingSenderId: '487822294670',
    projectId: 'door-alert-system',
    authDomain: 'door-alert-system.firebaseapp.com',
    databaseURL: 'https://door-alert-system-default-rtdb.firebaseio.com',
    storageBucket: 'door-alert-system.firebasestorage.app',
  );
}
